"""auto

Revision ID: 61416d988382
Revises: 
Create Date: 2026-01-23 19:10:07.389747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61416d988382'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('precio_extra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('precio_extra >= 0', name='ck_extras_precio_extra_ge_0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('franja', sa.String(length=50), nullable=False),
    sa.Column('turno', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('franja', 'turno', name='uq_horarios_franja_turno')
    )
    op.create_table('pistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('cubierta', sa.Boolean(), nullable=False),
    sa.Column('plazas', sa.Integer(), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('plazas > 0', name='ck_pistas_plazas_gt_0'),
    sa.CheckConstraint('precio_base >= 0', name='ck_pistas_precio_base_ge_0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_dni'), ['dni'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_rol_id'), ['rol_id'], unique=False)

    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pista_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['pista_id'], ['pistas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservas_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_pista_id'), ['pista_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('horarios_reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('horario_id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('precio >= 0', name='ck_horarios_reserva_precio_ge_0'),
    sa.ForeignKeyConstraint(['horario_id'], ['horarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reserva_id', 'horario_id', name='uq_horarios_reserva_reserva_horario')
    )
    with op.batch_alter_table('horarios_reserva', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horarios_reserva_horario_id'), ['horario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horarios_reserva_reserva_id'), ['reserva_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('horarios_reserva', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horarios_reserva_reserva_id'))
        batch_op.drop_index(batch_op.f('ix_horarios_reserva_horario_id'))

    op.drop_table('horarios_reserva')
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservas_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_reservas_pista_id'))
        batch_op.drop_index(batch_op.f('ix_reservas_fecha'))

    op.drop_table('reservas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_rol_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))
        batch_op.drop_index(batch_op.f('ix_usuarios_dni'))

    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('pistas')
    op.drop_table('horarios')
    op.drop_table('extras')
    # ### end Alembic commands ###
